mybatis:
  type-aliases-package: com.igalaxy.boot.domain
  mapper-locations: classpath:mapper/*/*.xml
  config-location: classpath:mybatis-config.xml
#    type-handlers-package:
spring:
  datasource:
    url: jdbc:mysql://igalaxy.iask.in:3306/boot?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 159258357
#    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
  thymeleaf:
    cache: false
    cache-period: 0
  template:
    cache: false
  redis:
    host: 101.200.148.203
    port: 26379
    password:
    pool:
      max-active: 8
  devtools:
    restart:
      enabled: true
      exclude: templates
logging:
  level:
    org.springframework.web: ERROR
    com.igalaxy.boot: DEBUG
    root: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
server:
  port: 8888

pay:
  wechat:
    unifiedorder_url: https://api.mch.weixin.qq.com/pay/unifiedorder
    notify_url: http://qg.igalaxy.com.cn/pay/wechat-notify
    appid: wx855e27a3d08ed53f
    mchid: 1370242202
    private_key: 66ff2be57bd12f21b72f96566b754a26

