mybatis:
    type-aliases-package: com.igalaxy.boot.domain
    mapper-locations: mapper/*/*.xml
#    type-handlers-package:
    config-location: mybatis-config.xml
spring:
  datasource:
    url: jdbc:mysql://igalaxy.iask.in:3306/cms?useUnicode=true&characterEncoding=UTF-8
    username: cms
    password: aF67ywe*df
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    host: 101.200.148.203
    port: 26379
    password:
    pool:
      max-active: 8
logging:
  level:
    org.springframework.web: ERROR
    com.igalaxy.boot: DEBUG
    root: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

